// cardsData.js - Star Wars Monopoly Cards Data
const cardsData = [
    { id: 1, stars: 1, isGold: false, name: "Movie Time" },
    { id: 2, stars: 1, isGold: false, name: "Galactic Fan" },
    { id: 3, stars: 1, isGold: false, name: "Tape Treasures" },
    { id: 4, stars: 1, isGold: false, name: "Epic Cinema" },
    { id: 5, stars: 1, isGold: false, name: "Star Struck" },
    { id: 6, stars: 1, isGold: false, name: "Message Incoming" },
    { id: 7, stars: 1, isGold: false, name: "My Only Hope" },
    { id: 8, stars: 1, isGold: false, name: "First Saber" },
    { id: 9, stars: 1, isGold: false, name: "Galaxy Dreams" },
    { id: 10, stars: 1, isGold: false, name: "Jedi Temple" },
    { id: 11, stars: 1, isGold: false, name: "Power Within" },
    { id: 12, stars: 1, isGold: false, name: "Sacred Hallways" },
    { id: 13, stars: 1, isGold: false, name: "Crystal Glow" },
    { id: 14, stars: 1, isGold: false, name: "Force Focus" },
    { id: 15, stars: 1, isGold: false, name: "Combat Training" },
    { id: 16, stars: 1, isGold: false, name: "Higher Learning" },
    { id: 17, stars: 1, isGold: false, name: "Force Struggle" },
    { id: 18, stars: 2, isGold: false, name: "Padawan Pride" },
    { id: 19, stars: 1, isGold: false, name: "Homestead" },
    { id: 20, stars: 1, isGold: false, name: "Blazing Dunes" },
    { id: 21, stars: 1, isGold: false, name: "Sandy Scouts" },
    { id: 22, stars: 1, isGold: false, name: "Busted Bolts" },
    { id: 23, stars: 1, isGold: false, name: "Droid Spa" },
    { id: 24, stars: 1, isGold: false, name: "Mos Merriment" },
    { id: 25, stars: 1, isGold: false, name: "Cantina Vibes" },
    { id: 26, stars: 2, isGold: false, name: "Bantha Milk" },
    { id: 27, stars: 2, isGold: false, name: "Tatooine Twilight" },
    { id: 28, stars: 1, isGold: false, name: "Grand Arena" },
    { id: 29, stars: 1, isGold: false, name: "Huttese Snacks" },
    { id: 30, stars: 1, isGold: false, name: "Fine Tuned" },
    { id: 31, stars: 1, isGold: false, name: "Race Rivals" },
    { id: 32, stars: 1, isGold: false, name: "Saboteur" },
    { id: 33, stars: 1, isGold: false, name: "Gear Up" },
    { id: 34, stars: 2, isGold: false, name: "Away We Go!" },
    { id: 35, stars: 2, isGold: false, name: "Narrow Victory" },
    { id: 36, stars: 2, isGold: false, name: "Tycoon Podracers" },
    { id: 37, stars: 1, isGold: false, name: "Opening Night" },
    { id: 38, stars: 1, isGold: false, name: "Grand Entrance" },
    { id: 39, stars: 1, isGold: false, name: "Space Symphony" },
    { id: 40, stars: 1, isGold: false, name: "Neon Grove" },
    { id: 41, stars: 1, isGold: false, name: "Cloud City" },
    { id: 42, stars: 2, isGold: false, name: "Bespin High Life" },
    { id: 43, stars: 2, isGold: false, name: "Sky-High Spread" },
    { id: 44, stars: 2, isGold: false, name: "Ready to Roll" },
    { id: 45, stars: 3, isGold: false, name: "Lucky Throw" },
    { id: 46, stars: 1, isGold: false, name: "Blueprints" },
    { id: 47, stars: 1, isGold: false, name: "Snowed In" },
    { id: 48, stars: 1, isGold: false, name: "Iced Projection" },
    { id: 49, stars: 2, isGold: false, name: "Hoth Hangar" },
    { id: 50, stars: 2, isGold: false, name: "Lost Again" },
    { id: 51, stars: 2, isGold: false, name: "Signal Found" },
    { id: 52, stars: 2, isGold: false, name: "System Online" },
    { id: 53, stars: 2, isGold: false, name: "Honorary Rebels" },
    { id: 54, stars: 3, isGold: false, name: "Furry Friend" },
    { id: 55, stars: 1, isGold: false, name: "Golden Greetings!" },
    { id: 56, stars: 1, isGold: false, name: "Mission Ready" },
    { id: 57, stars: 1, isGold: false, name: "Royal Etiquette" },
    { id: 58, stars: 2, isGold: false, name: "For the Alliance" },
    { id: 59, stars: 2, isGold: false, name: "Bun-tastic" },
    { id: 60, stars: 2, isGold: false, name: "Flight Time" },
    { id: 61, stars: 2, isGold: false, name: "Command Center" },
    { id: 62, stars: 3, isGold: false, name: "Ace Pilot" },
    { id: 63, stars: 3, isGold: false, name: "Triumph!" },
    { id: 64, stars: 1, isGold: false, name: "Treetop Town" },
    { id: 65, stars: 1, isGold: false, name: "Droid Devotion" },
    { id: 66, stars: 2, isGold: false, name: "Walker Win" },
    { id: 67, stars: 2, isGold: false, name: "Fashion Fur-ward" },
    { id: 68, stars: 2, isGold: false, name: "Net Loss" },
    { id: 69, stars: 2, isGold: false, name: "Up We Go!" },
    { id: 70, stars: 2, isGold: false, name: "Peg-E the Great" },
    { id: 71, stars: 3, isGold: false, name: "Wind Rider" },
    { id: 72, stars: 3, isGold: false, name: "Bonfire Boogie" },
    { id: 73, stars: 1, isGold: false, name: "Swamp Sanctuary" },
    { id: 74, stars: 2, isGold: false, name: "Wise Introduction" },
    { id: 75, stars: 2, isGold: false, name: "Heavy Lessons" },
    { id: 76, stars: 2, isGold: false, name: "Concentration" },
    { id: 77, stars: 2, isGold: false, name: "Tycoon Trials" },
    { id: 78, stars: 3, isGold: false, name: "Darth Whiskers" },
    { id: 79, stars: 3, isGold: false, name: "A-meow-sing" },
    { id: 80, stars: 3, isGold: false, name: "Force Master" },
    { id: 81, stars: 3, isGold: false, name: "Jedi Knight" },
    { id: 82, stars: 2, isGold: false, name: "Hutt HQ" },
    { id: 83, stars: 2, isGold: false, name: "Jabba's Offer" },
    { id: 84, stars: 2, isGold: false, name: "Mischief Maker" },
    { id: 85, stars: 2, isGold: false, name: "Service Mode" },
    { id: 86, stars: 2, isGold: false, name: "Delicacies?" },
    { id: 87, stars: 3, isGold: false, name: "Sail Barge" },
    { id: 88, stars: 3, isGold: false, name: "Skiff Spectacle" },
    { id: 89, stars: 3, isGold: false, name: "Rancor Charmer" },
    { id: 90, stars: 3, isGold: false, name: "Max Rebo Band" },
    { id: 91, stars: 2, isGold: false, name: "Tech Squad" },
    { id: 92, stars: 2, isGold: false, name: "Thumbs Up!" },
    { id: 93, stars: 2, isGold: false, name: "Mission Brief" },
    { id: 94, stars: 2, isGold: false, name: "Red Alert!" },
    { id: 95, stars: 3, isGold: false, name: "In a Bind" },
    { id: 96, stars: 3, isGold: false, name: "X-treme Ride" },
    { id: 97, stars: 3, isGold: false, name: "Tinkering Tech" },
    { id: 98, stars: 3, isGold: false, name: "Resistance Spirit" },
    { id: 99, stars: 4, isGold: false, name: "Commendations" },
    { id: 100, stars: 2, isGold: false, name: "Imperial Arrival" },
    { id: 101, stars: 2, isGold: false, name: "Shocking!" },
    { id: 102, stars: 2, isGold: false, name: "Galactic Charges" },
    { id: 103, stars: 3, isGold: false, name: "Emperor Whiskers" },
    { id: 104, stars: 3, isGold: false, name: "Tycoon Empire" },
    { id: 105, stars: 3, isGold: false, name: "Vader Envy" },
    { id: 106, stars: 3, isGold: false, name: "Sith Edition" },
    { id: 107, stars: 3, isGold: false, name: "Riveting Rivalry" },
    { id: 108, stars: 4, isGold: false, name: "The Last Goodbye" },
    { id: 109, stars: 2, isGold: false, name: "Kowakian Play" },
    { id: 110, stars: 2, isGold: false, name: "Oh My Bantha!" },
    { id: 111, stars: 3, isGold: false, name: "Tooka Snooze" },
    { id: 112, stars: 3, isGold: false, name: "Blurrg Blitz" },
    { id: 113, stars: 3, isGold: false, name: "Mynock Rush" },
    { id: 114, stars: 3, isGold: false, name: "Porg Pride" },
    { id: 115, stars: 3, isGold: false, name: "Wampa Angels" },
    { id: 116, stars: 4, isGold: false, name: "Tauntaun Cuddles" },
    { id: 117, stars: 4, isGold: false, name: "Purrgil Pursuit" },
    { id: 118, stars: 2, isGold: false, name: "Sands Ahead" },
    { id: 119, stars: 2, isGold: false, name: "Lost & Found" },
    { id: 120, stars: 3, isGold: false, name: "Fixer Upper" },
    { id: 121, stars: 3, isGold: false, name: "Delicious Delicacies" },
    { id: 122, stars: 3, isGold: false, name: "Market Day" },
    { id: 123, stars: 3, isGold: false, name: "Desert Deals" },
    { id: 124, stars: 4, isGold: false, name: "Jawa Jackpot" },
    { id: 125, stars: 4, isGold: false, name: "One of Us" },
    { id: 126, stars: 4, isGold: false, name: "Utinni & Goodbye" },
    { id: 127, stars: 2, isGold: false, name: "Docking Bay 94" },
    { id: 128, stars: 3, isGold: false, name: "Hero Han" },
    { id: 129, stars: 3, isGold: false, name: "Making the Jump" },
    { id: 130, stars: 3, isGold: false, name: "Hidden Cargo" },
    { id: 131, stars: 3, isGold: false, name: "Holo Chess" },
    { id: 132, stars: 4, isGold: false, name: "Blaster Blunder" },
    { id: 133, stars: 4, isGold: false, name: "Tickle Tactics" },
    { id: 134, stars: 4, isGold: true, name: "Warm & Fuzzy" },
    { id: 135, stars: 5, isGold: false, name: "Hyperspace Bound" },
    { id: 136, stars: 3, isGold: false, name: "Starkiller Base" },
    { id: 137, stars: 3, isGold: false, name: "Rescue Mission" },
    { id: 138, stars: 3, isGold: false, name: "Coast is Clear" },
    { id: 139, stars: 3, isGold: false, name: "Diversion Created" },
    { id: 140, stars: 4, isGold: false, name: "System Override" },
    { id: 141, stars: 4, isGold: false, name: "Thank the Maker!" },
    { id: 142, stars: 4, isGold: true, name: "Stealth Mode" },
    { id: 143, stars: 5, isGold: false, name: "Disguis-E" },
    { id: 144, stars: 5, isGold: false, name: "Escape Executed" },
    { id: 145, stars: 3, isGold: false, name: "New Crew" },
    { id: 146, stars: 3, isGold: false, name: "Fetch Friends" },
    { id: 147, stars: 3, isGold: false, name: "Sticky Fingers" },
    { id: 148, stars: 4, isGold: false, name: "Tiny Tycoon" },
    { id: 149, stars: 4, isGold: false, name: "Compact Curiosity" },
    { id: 150, stars: 4, isGold: true, name: "Side by Side" },
    { id: 151, stars: 5, isGold: false, name: "Force Rising" },
    { id: 152, stars: 5, isGold: false, name: "Beskar Best" },
    { id: 153, stars: 5, isGold: true, name: "Ms Mandalore" },
    { id: 154, stars: 3, isGold: false, name: "Vader's Welcome" },
    { id: 155, stars: 4, isGold: false, name: "In Style" },
    { id: 156, stars: 4, isGold: false, name: "Sith & Sips" },
    { id: 157, stars: 4, isGold: false, name: "Force Fetch" },
    { id: 158, stars: 4, isGold: true, name: "Darth Volley" },
    { id: 159, stars: 5, isGold: false, name: "Beach Brooding" },
    { id: 160, stars: 5, isGold: false, name: "Dark Side BBQ" },
    { id: 161, stars: 5, isGold: false, name: "Sizzling Farewell" },
    { id: 162, stars: 5, isGold: true, name: "Galactic Bond" },
    { id: 163, stars: 4, isGold: false, name: "Kashyyyk" },
    { id: 164, stars: 4, isGold: false, name: "Warm Welcome" },
    { id: 165, stars: 4, isGold: false, name: "Mini Wookiee" },
    { id: 166, stars: 4, isGold: false, name: "Holocall" },
    { id: 167, stars: 4, isGold: true, name: "Chewie's Curls" },
    { id: 168, stars: 5, isGold: false, name: "Wee Lil' Wookiee" },
    { id: 169, stars: 5, isGold: false, name: "Bullseye!" },
    { id: 170, stars: 5, isGold: true, name: "Galaxy Gazing" },
    { id: 171, stars: 5, isGold: true, name: "Furry Farewell" },
    { id: 172, stars: 4, isGold: false, name: "X-wing" },
    { id: 173, stars: 4, isGold: false, name: "Star Destroyer" },
    { id: 174, stars: 4, isGold: false, name: "Vader's TIE Fighter" },
    { id: 175, stars: 4, isGold: true, name: "Sandcrawler" },
    { id: 176, stars: 5, isGold: false, name: "Death Star" },
    { id: 177, stars: 5, isGold: false, name: "X-34 Landspeeder" },
    { id: 178, stars: 5, isGold: true, name: "TIE Fighter" },
    { id: 179, stars: 5, isGold: true, name: "AT-AT" },
    { id: 180, stars: 5, isGold: true, name: "Millennium Falcon" },
    { id: 181, stars: 4, isGold: false, name: "Eopie Love" },
    { id: 182, stars: 4, isGold: false, name: "Reality Check" },
    { id: 183, stars: 5, isGold: false, name: "Ultimate Fans" },
    { id: 184, stars: 5, isGold: false, name: "Force It Over" },
    { id: 185, stars: 5, isGold: false, name: "Master of Merch" },
    { id: 186, stars: 5, isGold: true, name: "Replica Rivalry" },
    { id: 187, stars: 5, isGold: true, name: "Credits Incoming" },
    { id: 188, stars: 5, isGold: true, name: "Astro-Bites" },
    { id: 189, stars: 5, isGold: true, name: "Space Selfies" },
    { id: 190, stars: 4, isGold: true, name: "Luke Skywalker" },
    { id: 191, stars: 4, isGold: true, name: "Princess Leia" },
    { id: 192, stars: 4, isGold: true, name: "Han Solo" },
    { id: 193, stars: 4, isGold: true, name: "Chewbacca" },
    { id: 194, stars: 4, isGold: true, name: "Yoda" },
    { id: 195, stars: 4, isGold: true, name: "R2-D2" },
    { id: 196, stars: 4, isGold: true, name: "BB-8" },
    { id: 197, stars: 4, isGold: true, name: "The Mandalorian" },
    { id: 198, stars: 4, isGold: true, name: "Grogu" },
    { id: 199, stars: 3, isGold: false, name: "Empire Needs You" },
    { id: 200, stars: 3, isGold: false, name: "Imperial Academy" },
    { id: 201, stars: 4, isGold: false, name: "Galactic Gauntlet" },
    { id: 202, stars: 4, isGold: false, name: "Naps 101" },
    { id: 203, stars: 4, isGold: true, name: "Doodle Duty" },
    { id: 204, stars: 5, isGold: false, name: "Missed the Mark" },
    { id: 205, stars: 5, isGold: false, name: "Pawpatine" },
    { id: 206, stars: 5, isGold: true, name: "Short-Trooper" },
    { id: 207, stars: 5, isGold: true, name: "Graduation Day" },
    { id: 208, stars: 4, isGold: false, name: "A Royal Welcome" },
    { id: 209, stars: 4, isGold: false, name: "That's Not Yours" },
    { id: 210, stars: 4, isGold: false, name: "Not So Easy" },
    { id: 211, stars: 4, isGold: true, name: "Aqua Encounter" },
    { id: 212, stars: 4, isGold: true, name: "Gungan Couture" },
    { id: 213, stars: 5, isGold: false, name: "Boss Nass" },
    { id: 214, stars: 5, isGold: false, name: "Super Slurp" },
    { id: 215, stars: 5, isGold: true, name: "Deep Sea Ride" },
    { id: 216, stars: 5, isGold: true, name: "Friendly Fire" },
    { id: 217, stars: 4, isGold: false, name: "Outpost Riders" },
    { id: 218, stars: 4, isGold: false, name: "Critter Caravan" },
    { id: 219, stars: 4, isGold: true, name: "Jam-Packed" },
    { id: 220, stars: 4, isGold: true, name: "Rebel Relics" },
    { id: 221, stars: 5, isGold: false, name: "Assembly Required" },
    { id: 222, stars: 5, isGold: false, name: "Sandslide" },
    { id: 223, stars: 5, isGold: true, name: "Wreckage" },
    { id: 224, stars: 5, isGold: true, name: "Direct Connection" },
    { id: 225, stars: 5, isGold: true, name: "Planet Top Hat" },
    { id: 226, stars: 4, isGold: true, name: "Secret Exchange" },
    { id: 227, stars: 4, isGold: true, name: "Thrill Ride" },
    { id: 228, stars: 4, isGold: true, name: "Holo Schemes" },
    { id: 229, stars: 5, isGold: false, name: "Heart exe" },
    { id: 230, stars: 5, isGold: false, name: "Eye of Aldhani" },
    { id: 231, stars: 5, isGold: false, name: "Behind Enemy Lines" },
    { id: 232, stars: 5, isGold: true, name: "What are those?!" },
    { id: 233, stars: 5, isGold: true, name: "Vault Found" },
    { id: 234, stars: 5, isGold: true, name: "Heist Complete!" }
];