// cardsData.js - Monopoly GO Cards Data
const cardsData = [
    { id: 1, stars: 1, isGold: false, name: "Alpine Trail" },
    { id: 2, stars: 1, isGold: false, name: "Matterhorn" },
    { id: 3, stars: 1, isGold: false, name: "Paraglide Joy" },
    { id: 4, stars: 1, isGold: false, name: "Meadow Maidens" },
    { id: 5, stars: 1, isGold: false, name: "Alpine Melody" },
    { id: 6, stars: 1, isGold: false, name: "Cliff King" },
    { id: 7, stars: 1, isGold: false, name: "Swiss Dip" },
    { id: 8, stars: 1, isGold: false, name: "Mountain Riders" },
    { id: 9, stars: 1, isGold: false, name: "Folklore Fest" },
    { id: 10, stars: 1, isGold: false, name: "Backyard Oasis" },
    { id: 11, stars: 1, isGold: false, name: "Picnic Setup" },
    { id: 12, stars: 1, isGold: false, name: "Snack Stack" },
    { id: 13, stars: 1, isGold: false, name: "Cornhole Awaits" },
    { id: 14, stars: 1, isGold: false, name: "Flutter By" },
    { id: 15, stars: 1, isGold: false, name: "Picnic Thieves" },
    { id: 16, stars: 1, isGold: false, name: "Summer Gnome" },
    { id: 17, stars: 1, isGold: false, name: "Fuchsia Friend" },
    { id: 18, stars: 2, isGold: false, name: "Whirligig" },
    { id: 19, stars: 1, isGold: false, name: "Swim Trunks" },
    { id: 20, stars: 1, isGold: false, name: "Sunscreen" },
    { id: 21, stars: 1, isGold: false, name: "Sun Hat" },
    { id: 22, stars: 1, isGold: false, name: "Shades" },
    { id: 23, stars: 1, isGold: false, name: "Beach Umbrella" },
    { id: 24, stars: 1, isGold: false, name: "Cooler" },
    { id: 25, stars: 1, isGold: false, name: "Sand Bucket" },
    { id: 26, stars: 2, isGold: false, name: "Beach Ball" },
    { id: 27, stars: 2, isGold: false, name: "Towel" },
    { id: 28, stars: 1, isGold: false, name: "Lizzie Lounges" },
    { id: 29, stars: 1, isGold: false, name: "Sandy Masterpiece" },
    { id: 30, stars: 1, isGold: false, name: "If I fit?" },
    { id: 31, stars: 1, isGold: false, name: "Mr Merman" },
    { id: 32, stars: 1, isGold: false, name: "Seaside Watch" },
    { id: 33, stars: 1, isGold: false, name: "Beach Beauty" },
    { id: 34, stars: 2, isGold: false, name: "Boss Spike" },
    { id: 35, stars: 2, isGold: false, name: "Snack Thief" },
    { id: 36, stars: 2, isGold: false, name: "Flippin' Fun" },
    { id: 37, stars: 1, isGold: false, name: "Telescope Time" },
    { id: 38, stars: 1, isGold: false, name: "Cosmic Cocoa" },
    { id: 39, stars: 1, isGold: false, name: "Just Resting" },
    { id: 40, stars: 1, isGold: false, name: "Starstruck" },
    { id: 41, stars: 2, isGold: false, name: "Tycoon Stars" },
    { id: 42, stars: 2, isGold: false, name: "A Real Hoot" },
    { id: 43, stars: 2, isGold: false, name: "Starlit Voyage" },
    { id: 44, stars: 2, isGold: false, name: "Charting Stars" },
    { id: 45, stars: 2, isGold: false, name: "Meteor Shower" },
    { id: 46, stars: 1, isGold: false, name: "Beach Huts" },
    { id: 47, stars: 1, isGold: false, name: "Seaside Setup" },
    { id: 48, stars: 1, isGold: false, name: "Wave Chaser" },
    { id: 49, stars: 2, isGold: false, name: "Sandsational" },
    { id: 50, stars: 2, isGold: false, name: "Seaside Rock" },
    { id: 51, stars: 2, isGold: false, name: "Makeshift Brolly" },
    { id: 52, stars: 2, isGold: false, name: "After the Rain" },
    { id: 53, stars: 2, isGold: false, name: "Fish & Chips" },
    { id: 54, stars: 3, isGold: false, name: "Golden Hour" },
    { id: 55, stars: 1, isGold: false, name: "Wet Dog" },
    { id: 56, stars: 1, isGold: false, name: "Buried Treasure" },
    { id: 57, stars: 2, isGold: false, name: "Spa Day" },
    { id: 58, stars: 2, isGold: false, name: "Cruisin'" },
    { id: 59, stars: 2, isGold: false, name: "Pup Pops" },
    { id: 60, stars: 2, isGold: false, name: "Dreamboat Dog" },
    { id: 61, stars: 2, isGold: false, name: "Sandy Paws" },
    { id: 62, stars: 3, isGold: false, name: "Home Sweet Home" },
    { id: 63, stars: 3, isGold: false, name: "Tuckered Out" },
    { id: 64, stars: 1, isGold: false, name: "Stash O'Sparks" },
    { id: 65, stars: 2, isGold: false, name: "Pinwheelin'" },
    { id: 66, stars: 2, isGold: false, name: "Star Spangled" },
    { id: 67, stars: 2, isGold: false, name: "Hot Rod Hero" },
    { id: 68, stars: 2, isGold: false, name: "Hot Grill Summer" },
    { id: 69, stars: 3, isGold: false, name: "Red, White & Yum" },
    { id: 70, stars: 3, isGold: false, name: "Sky Salute" },
    { id: 71, stars: 3, isGold: false, name: "Spark-tacular" },
    { id: 72, stars: 3, isGold: false, name: "Do Not Disturb" },
    { id: 73, stars: 2, isGold: false, name: "Here We Go!" },
    { id: 74, stars: 2, isGold: false, name: "Caramel Apples" },
    { id: 75, stars: 2, isGold: false, name: "Game On" },
    { id: 76, stars: 2, isGold: false, name: "Prize Booth" },
    { id: 77, stars: 2, isGold: false, name: "Hot Dog Champ" },
    { id: 78, stars: 3, isGold: false, name: "Wheel of Wonder" },
    { id: 79, stars: 3, isGold: false, name: "Ride the Magic" },
    { id: 80, stars: 3, isGold: false, name: "Cotton Candy" },
    { id: 81, stars: 4, isGold: false, name: "Farewell Haul" },
    { id: 82, stars: 2, isGold: false, name: "Aloha Skies" },
    { id: 83, stars: 2, isGold: false, name: "Surf's Up!" },
    { id: 84, stars: 2, isGold: false, name: "Turtle Tourists" },
    { id: 85, stars: 2, isGold: false, name: "Canoe Crew" },
    { id: 86, stars: 3, isGold: false, name: "Island Melody" },
    { id: 87, stars: 3, isGold: false, name: "Lei'd Back" },
    { id: 88, stars: 3, isGold: false, name: "Tropical Treat" },
    { id: 89, stars: 3, isGold: false, name: "The Hula" },
    { id: 90, stars: 4, isGold: false, name: "Fire Dance" },
    { id: 91, stars: 2, isGold: false, name: "Chill Wagon" },
    { id: 92, stars: 2, isGold: false, name: "Icy Icon" },
    { id: 93, stars: 3, isGold: false, name: "Sky-High Swirl" },
    { id: 94, stars: 3, isGold: false, name: "Bowl of Joy" },
    { id: 95, stars: 3, isGold: false, name: "Cherry on Top" },
    { id: 96, stars: 3, isGold: false, name: "Cone Malone" },
    { id: 97, stars: 3, isGold: false, name: "Uncharted Flavors" },
    { id: 98, stars: 4, isGold: false, name: "Scoop Down" },
    { id: 99, stars: 4, isGold: false, name: "Frozen Frame" },
    { id: 100, stars: 2, isGold: false, name: "Berry Big Fan" },
    { id: 101, stars: 2, isGold: false, name: "Float Fun" },
    { id: 102, stars: 3, isGold: false, name: "Prized Goods" },
    { id: 103, stars: 3, isGold: false, name: "Strawberry Queen" },
    { id: 104, stars: 3, isGold: false, name: "Berry Bliss" },
    { id: 105, stars: 3, isGold: false, name: "Freshly Baked" },
    { id: 106, stars: 4, isGold: false, name: "Skyberry" },
    { id: 107, stars: 4, isGold: false, name: "Berry Berry" },
    { id: 108, stars: 4, isGold: true, name: "Say Strawberry!" },
    { id: 109, stars: 2, isGold: false, name: "The Maypole" },
    { id: 110, stars: 3, isGold: false, name: "Flower Crowns" },
    { id: 111, stars: 3, isGold: false, name: "Summer Bouquet" },
    { id: 112, stars: 3, isGold: false, name: "Blooming Valley" },
    { id: 113, stars: 3, isGold: false, name: "Smörgåsbord!" },
    { id: 114, stars: 4, isGold: false, name: "Maypole Queen" },
    { id: 115, stars: 4, isGold: false, name: "Kubb" },
    { id: 116, stars: 4, isGold: false, name: "Jordgubbstårta" },
    { id: 117, stars: 4, isGold: true, name: "Petal Party" },
    { id: 118, stars: 3, isGold: false, name: "Hola Oaxaca" },
    { id: 119, stars: 3, isGold: false, name: "Sweet Sips" },
    { id: 120, stars: 3, isGold: false, name: "Guelaguetza" },
    { id: 121, stars: 3, isGold: false, name: "Taco Time!" },
    { id: 122, stars: 4, isGold: false, name: "Puppet Parade" },
    { id: 123, stars: 4, isGold: false, name: "Band Together" },
    { id: 124, stars: 4, isGold: false, name: "Fabric Finds" },
    { id: 125, stars: 4, isGold: true, name: "Marmota" },
    { id: 126, stars: 5, isGold: false, name: "Oaxaca Momentos" },
    { id: 127, stars: 3, isGold: false, name: "Ready or Not" },
    { id: 128, stars: 3, isGold: false, name: "Cannonball!" },
    { id: 129, stars: 4, isGold: false, name: "Tug" },
    { id: 130, stars: 4, isGold: false, name: "-O-" },
    { id: 131, stars: 4, isGold: false, name: "War" },
    { id: 132, stars: 4, isGold: true, name: "Gimme S'more" },
    { id: 133, stars: 5, isGold: false, name: "Twilight Trail" },
    { id: 134, stars: 5, isGold: true, name: "Camp Besties" },
    { id: 135, stars: 3, isGold: false, name: "Open Road" },
    { id: 136, stars: 3, isGold: false, name: "Lost Bot" },
    { id: 137, stars: 4, isGold: false, name: "This Way" },
    { id: 138, stars: 4, isGold: false, name: "Cadillac Ranch" },
    { id: 139, stars: 4, isGold: false, name: "Diner Delight" },
    { id: 140, stars: 4, isGold: true, name: "Tire Trouble" },
    { id: 141, stars: 5, isGold: false, name: "Oatman Burros" },
    { id: 142, stars: 5, isGold: false, name: "California Nights" },
    { id: 143, stars: 5, isGold: true, name: "Rickety Rockers" },
    { id: 144, stars: 3, isGold: false, name: "Anticipation" },
    { id: 145, stars: 3, isGold: false, name: "Besties Forever" },
    { id: 146, stars: 4, isGold: false, name: "Top Dog Award" },
    { id: 147, stars: 4, isGold: true, name: "One Last Photo" },
    { id: 148, stars: 4, isGold: true, name: "Pizza Party" },
    { id: 149, stars: 5, isGold: false, name: "Straight A's" },
    { id: 150, stars: 5, isGold: false, name: "Farewell Hugs" },
    { id: 151, stars: 5, isGold: false, name: "Time's Up" },
    { id: 152, stars: 5, isGold: true, name: "Freedom, Finally" },
    { id: 153, stars: 3, isGold: false, name: "Lavender Fields" },
    { id: 154, stars: 4, isGold: false, name: "Tea Time" },
    { id: 155, stars: 4, isGold: true, name: "Fresh Pickings" },
    { id: 156, stars: 4, isGold: true, name: "Market Mayhem" },
    { id: 157, stars: 5, isGold: false, name: "Pretty Picnic" },
    { id: 158, stars: 5, isGold: false, name: "Steps of Vence" },
    { id: 159, stars: 5, isGold: true, name: "Afternoon Nap" },
    { id: 160, stars: 5, isGold: true, name: "Vélo Voyage" },
    { id: 161, stars: 6, isGold: false, name: "Gordes Provence" },
    { id: 162, stars: 4, isGold: false, name: "Flamingo Float" },
    { id: 163, stars: 4, isGold: true, name: "Sofia Soaks" },
    { id: 164, stars: 4, isGold: true, name: "Splash Kit" },
    { id: 165, stars: 5, isGold: false, name: "Boomin'" },
    { id: 166, stars: 5, isGold: false, name: "Ice Scream!" },
    { id: 167, stars: 5, isGold: true, name: "Solar Powered" },
    { id: 168, stars: 5, isGold: true, name: "Pool Panic" },
    { id: 169, stars: 6, isGold: false, name: "Water Fight" },
    { id: 170, stars: 6, isGold: true, name: "Splish Splash" },
    { id: 171, stars: 4, isGold: true, name: "Sweet Plans" },
    { id: 172, stars: 4, isGold: true, name: "Sign Time" },
    { id: 173, stars: 5, isGold: false, name: "Prep Progress" },
    { id: 174, stars: 5, isGold: false, name: "First Customer" },
    { id: 175, stars: 5, isGold: true, name: "Worth the Squeeze" },
    { id: 176, stars: 5, isGold: true, name: "Quick Stir" },
    { id: 177, stars: 6, isGold: false, name: "Golden Success" },
    { id: 178, stars: 6, isGold: false, name: "Cha-Ching!" },
    { id: 179, stars: 6, isGold: true, name: "Cheers" },
    { id: 180, stars: 3, isGold: false, name: "Jet Set Go!" },
    { id: 181, stars: 4, isGold: false, name: "Fur'st Class" },
    { id: 182, stars: 4, isGold: false, name: "Bon Bagage" },
    { id: 183, stars: 4, isGold: true, name: "Lotta Yacht-a" },
    { id: 184, stars: 4, isGold: true, name: "Right Direction" },
    { id: 185, stars: 5, isGold: false, name: "Captain Jon" },
    { id: 186, stars: 5, isGold: false, name: "Luxe Lift-Off" },
    { id: 187, stars: 5, isGold: false, name: "Wake Queen" },
    { id: 188, stars: 5, isGold: true, name: "Go! Cruise" },
    { id: 189, stars: 4, isGold: false, name: "Private Paradise" },
    { id: 190, stars: 4, isGold: true, name: "Cabana King" },
    { id: 191, stars: 4, isGold: true, name: "Lagoon Bloom" },
    { id: 192, stars: 5, isGold: false, name: "Jungle Spa" },
    { id: 193, stars: 5, isGold: false, name: "Parrot Perch" },
    { id: 194, stars: 5, isGold: false, name: "Acai Bowl" },
    { id: 195, stars: 5, isGold: true, name: "Limbo Legend" },
    { id: 196, stars: 5, isGold: true, name: "Spin Master M" },
    { id: 197, stars: 5, isGold: true, name: "Conga!" }
];